version: "3.7"

networks:
  default:
    driver: overlay
  gateway:
    external: true

services:
  liquidity-pools-db:
    image: postgres:15
    ports:
      - "23798:5432"
    environment:
      POSTGRES_DB: "liquidity_pools_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    logging:
      driver: json-file
    networks:
      - default

  liquidity-pools-processor:
    image: liquidity-pools-indexer:latest
    depends_on:
      - liquidity-pools-db
    environment:
      NODE_ENV: "self-hosted"
      CHAIN: "hydration"
      DB_PORT: 5432
      DB_NAME: "liquidity_pools_db"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_HOST: "liquidity-pools-db"
    ports:
      - "3030:3030"
    networks:
      - default
    command:
      - sh
      - -c
      - "sqd migration:apply && sqd process:prod"

  liquidity-pools-api:
    image: liquidity-pools-indexer:latest
    depends_on:
      - liquidity-pools-processor
    environment:
      NODE_ENV: "self-hosted"
      CHAIN: "hydration"
      GQL_PORT: 8080
      DB_PORT: 5432
      DB_NAME: "liquidity_pools_db"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_HOST: "liquidity-pools-db"
    ports:
      - "8080:8080"
    networks:
      - default
      - gateway
    logging:
      driver: json-file
    # Wait 15s for processor complete DB migrations and create service tables which are required for api app.
    # API app needs to run its own DB migrations to set up DB subscriptions.
    command:
      - sh
      - -c
      - "sleep 10 && sqd api:prod"
    deploy:
      replicas: 3
      labels:
        traefik.http.routers.hrds.rule: Host(`liquidity-pools-indexer.play.hydration.cloud`)
        traefik.http.routers.hrds.tls: "true"
        traefik.http.routers.hrds.tls.certresolver: myresolver
        traefik.http.services.hrds.loadbalancer.server.port: "8080"
