# This workflow can be invoked only from caller workflow.
# More information about Reusing workflows - https://docs.github.com/en/actions/using-workflows/reusing-workflows

# Build indexers production ready files. Build results will be saved as artifacts with names, passed
# in "liquidity-pools-build-artifact-name" and "dictionary-build-artifact-name" inputs.

name: "Reusable :: Build and Publish Docker images"

on:
  workflow_call:
    inputs:
      liquidity-pools-build-artifact-name:
        required: true
        type: string
      dictionary-build-artifact-name:
        required: true
        type: string
    secrets:
      GHCR_AUTH_TOKEN:
        required: true

env:
  ACTIONS_STEP_DEBUG: true
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up docker qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_AUTH_TOKEN }}


      - name: "Sanitize branch name"
        id: branch-name-as-tag
        shell: bash
        run: |
          sudo chmod +x ./scripts/ci/gh-actions-get-branch-name-as-image-tag.sh
          echo "##[set-output name=name;]$(./scripts/ci/gh-actions-get-branch-name-as-image-tag.sh "$GITHUB_EVENT_NAME" "$GITHUB_REF" "$GITHUB_BASE_REF")"

      - name: Set DOCKER_REPO_TAGGED based on branch or tag
        env:
          BRANCH_NAME: ${{ steps.branch-name-as-tag.outputs.name }}
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${BRANCH_NAME}:WIP" >> $GITHUB_ENV
          fi

      - name: Set Docker metadata for Liquidity Pools indexer
        id: liquidity-pools-ind-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/liquidity-pools-indexer
          tags: |
            ${{env.IMAGE_TAG}}
            ${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{github.repository_owner}}/hyd-data-lake
            org.opencontainers.image.description=Hydration Liquidity Pools indexer image
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=liquidity-pools-indexer

      - name: Build and push Docker image of Liquidity Pools indexer
        id: liquidity-pools-indexer-push
        uses: docker/build-push-action@v6
        with:
          context: ./indexers/liquidity-pools/
          push: true
          tags: ${{ steps.liquidity-pools-ind-meta.outputs.tags }}
          labels: ${{ steps.liquidity-pools-ind-meta.outputs.labels }}


      - name: Set Docker metadata for Storage Dictionary indexer
        id: storage-dictionary-ind-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/storage-dictionary-indexer
          tags: |
            ${{env.IMAGE_TAG}}
            ${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{github.repository_owner}}/hyd-data-lake
            org.opencontainers.image.description=Hydration Storage Dictionary indexer image
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=storage-dictionary-indexer

      - name: Build and push Docker image of Storage Dictionary indexer
        id: storage-dictionary-indexer-push
        uses: docker/build-push-action@v6
        with:
          context: ./indexers/storage-dictionary/
          push: true
          tags: ${{ steps.storage-dictionary-ind-meta.outputs.tags }}
          labels: ${{ steps.storage-dictionary-ind-meta.outputs.labels }}
            

#      - name: Build and publish image for main branch or tag push event
#        env:
#          DOCKER_REPO_TAGGED: ${{ env.DOCKER_REPO_TAGGED }}
#        working-directory: indexers/liquidity-pools/
#        run: |
#          docker buildx build \
#          --platform linux/amd64,linux/arm64 \
#          --label "org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/liquidity-pools-indexer" \
#          --label "org.opencontainers.image.description=Hydration Liquidity Pools indexer image" \
#          --label "org.opencontainers.image.licenses=MIT" \
#          --push \
#          -t ${DOCKER_REPO_TAGGED} \
#          -f Dockerfile \
#          .
#
#      - name: Pull image from GitHub Container Registry
#        run: docker pull ghcr.io/${{ github.repository_owner }}/liquidity-pools-indexer:${{env.IMAGE_TAG}}
#
#      - name: Tag image with name and version tag
#        run: docker tag ghcr.io/${{ github.repository_owner }}/liquidity-pools-indexer:${{env.IMAGE_TAG}} liquidity-pools-indexer:${{env.IMAGE_TAG}}
#
#      - name: Push image to Docker Hub
#        run: docker push liquidity-pools-indexer:${{env.IMAGE_TAG}}



          
#      - name: set docker metadata
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: |
#            ${{ github.repository_owner }}/liquidity-pools-indexer
#          tags: |
#            latest
##            type=schedule,pattern=nightly
##            type=schedule,prefix=nightly-,pattern={{date 'YYYYMMDD'}}
##            type=ref,event=branch
##            type=ref,event=pr
##            type=ref,event=tag
##            type=semver,pattern={{version}}
##            type=semver,pattern={{major}}.{{minor}}
##            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
##            type=sha,format=long,prefix=,suffix=
#          labels: |
#            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/hyd-data-lake
#            org.opencontainers.image.description=Hydration Liquidity Pools indexer image
#            org.opencontainers.image.licenses=MIT
#
#      - name: build and push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          target: final
#          push: false
#          load: true
#          file: indexers/liquidity-pools/Dockerfile
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          no-cache: true
#          pull: true

#      - name: "Run liquidity-pools indexer api"
#        shell: bash
#        working-directory: ./indexers/liquidity-pools
#        run: |
#          docker build \
#          . \
#          -t liquidity-pools-indexer:latest
#          --label "org.opencontainers.image.source=https://github.com/mckrava/hyd-data-lake" \
#          --label "org.opencontainers.image.description=Hydration Liquidity Pools indexer image" \
#          --label "org.opencontainers.image.licenses=MIT" \
          
          
          
      


