# Run tests for Liquidity Pools API

name: "Liquidity Pools and Storage Dictionary API testing"

on:
  push:
    branches:
      - "fix/**"
      - "feat/**"
      - "develop"
  pull_request:
    types:
      - "opened"
    branches:
      - "develop"

jobs:
  # Build Indexers
#  build:
#    name: "Build indexers"
#    uses: ./.github/workflows/_called_build_indexers.yml
#    with:
#      liquidity-pools-build-artifact-name: liquidity-pools-build-files
#      dictionary-build-artifact-name: dictionary-build-files
#    secrets:
#      gh_token: ${{ secrets.GITHUB_TOKEN }}
#
#  liq-pools-indexer-with-no-dict-test:
#    name: "Liq.pools indexer with no dictionary API test"
#    needs: build
#    if: ${{ needs.build.result=='success' }}
#    uses: ./.github/workflows/_called_run-liq-pools-indexer-api-test.yml
#    with:
#      liquidity-pools-build-artifact-name: liquidity-pools-build-files
#      dictionary-build-artifact-name: dictionary-build-files
#      is-liq-pools-indexer-with-dictionary: false
#      liq-pools-indexer-from-block: 4187498
#      liq-pools-indexer-to-block: 4198534
#      process-lbp-pools: true
#      process-xyk-pools: true
#      process-omnipools: false
#      process-stablepools: false
#
#  liq-pools-indexer-with-dict-test:
#    name: "Liq.pools indexer with dictionary API test"
#    needs: build
#    if: ${{ needs.build.result=='success' }}
#    uses: ./.github/workflows/_called_run-liq-pools-indexer-api-test.yml
#    with:
#      liquidity-pools-build-artifact-name: liquidity-pools-build-files
#      dictionary-build-artifact-name: dictionary-build-files
#      is-liq-pools-indexer-with-dictionary: true
#      liq-pools-indexer-from-block: 4187498
#      liq-pools-indexer-to-block: 4198534
#      storage-dictionary-from-block: 4187498
#      storage-dictionary-to-block: 4198534
#      process-lbp-pools: true
#      process-xyk-pools: true
#      process-omnipools: false
#      process-stablepools: false
#
#  storage-dictionary-test:
#    name: "Storage Dictionary API test"
#    needs: build
#    if: ${{ needs.build.result=='success' }}
#    uses: ./.github/workflows/_called_run-storage-dict-api-test.yml
#    with:
#      dictionary-build-artifact-name: dictionary-build-files
#      from-block: 4187498
#      to-block: 4198534
#      process-lbp-pools: true
#      process-xyk-pools: false
#      process-omnipools: false
#      process-stablepools: false
